# Generated by Django 4.0.3 on 2022-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nny', '0002_remove_user_eye_remove_user_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=False, max_length=255, unique=True),
        ),
    ]
