# Generated by Django 4.1 on 2022-08-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nny', '0002_remove_user_eyes_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eyes',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
