# Generated by Django 4.1 on 2022-08-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nny', '0004_remove_user_eyes_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='eyes',
        ),
        migrations.AddField(
            model_name='user',
            name='eyes',
            field=models.CharField(default='', max_length=40),
        ),
    ]
